version: '3'
services:
  flask:
    build: .
    command: gunicorn -w 4 -b 0.0.0.0:5000 webservice:app --reload
    environment:
      - FLASK_APP=webservice.py
      - FLASK_DEBUG=1
    ports:
      - "5000:5000"
    volumes:
      - ./:/root